# Generated by Django 2.2.4 on 2020-01-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_date'], 'verbose_name': 'Блоги', 'verbose_name_plural': 'Блоги'},
        ),
    ]
